<a href="https://colab.research.google.com/github/AmirGhnbr/Tweet-classification-tensorflow/blob/dev-branch/Tweet_classification_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This project aims to classify a particular tweet is related to disaster or not.

## make sure using GPU

In [1]:
!nvidia-smi

Tue Oct 11 17:37:35 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P8    11W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
# get the helper function
!wget https://raw.githubusercontent.com/AmirGhnbr/Tweet-classification-tensorflow/main/helper.py

--2022-10-11 17:37:36--  https://raw.githubusercontent.com/AmirGhnbr/Tweet-classification-tensorflow/main/helper.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10566 (10K) [text/plain]
Saving to: ‘helper.py’

helper.py           100%[===================>]  10.32K  --.-KB/s    in 0s      

2022-10-11 17:37:36 (28.6 MB/s) - ‘helper.py’ saved [10566/10566]



In [3]:
from helper import unzip_data, create_tensorboard_callback, plot_loss_curves, compare_historys

## Download text dataset from [Kaggle](https://www.kaggle.com/c/nlp-getting-started/data)

In [4]:
!wget "https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip"

--2022-10-11 17:37:41--  https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.212.128, 172.217.214.128, 172.253.114.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.212.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 607343 (593K) [application/zip]
Saving to: ‘nlp_getting_started.zip’

nlp_getting_started 100%[===================>] 593.11K  --.-KB/s    in 0.008s  

2022-10-11 17:37:41 (73.4 MB/s) - ‘nlp_getting_started.zip’ saved [607343/607343]



In [5]:
unzip_data("nlp_getting_started.zip")

## Visualize the dataset

In [6]:
import pandas as pd

train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")
train_df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [7]:
train_df_shuffled = train_df.sample(frac=1, random_state=42)
train_df_shuffled.head(5)

id      keyword               location  \
2644  3796  destruction                    NaN   
2227  3185       deluge                    NaN   
5448  7769       police                     UK   
132    191   aftershock                    NaN   
6845  9810       trauma  Montgomery County, MD   

                                                   text  target  
2644  So you have a new weapon that can cause un-ima...       1  
2227  The f$&amp;@ing things I do for #GISHWHES Just...       0  
5448  DT @georgegalloway: RT @Galloway4Mayor: ‰ÛÏThe...       1  
132   Aftershock back to school kick off was great. ...       0  
6845  in response to trauma Children of Addicts deve...       0

In [8]:
train_df_shuffled["target"].value_counts()

0    4342
1    3271
Name: target, dtype: int64

In [9]:
# Lets see some random tweets
import random
random_index = random.randint(0, len(train_df_shuffled)-5)
for row in train_df_shuffled[["text", "target"]][random_index:random_index+5].itertuples():
  _, text, target = row
  print(f"Target: {target}", "(real disaster)" if target > 0 else "(not real disaster)")
  print(f"Text:\n{text}\n")
  print("---\n")

Target: 0 (not real disaster)
Text:
YOUR PHONE IS SPYING ON YOU! Hidden Back Door NSA Data Mining Software | THE FINANCIAL ARMAGEDDON BLOG http://t.co/qyCw5JJaj1

---

Target: 1 (real disaster)
Text:
Zeal is a volcano the peak of which the grass of indecisiveness does not grow

---

Target: 0 (not real disaster)
Text:
you can stop panicking ?????? @ogtomd  https://t.co/ZvRE6fFNyD

---

Target: 0 (not real disaster)
Text:
#Spotlight Take Me To Paradise by Arsonist MC #WNIAGospel http://t.co/1he4UfaWZm @arsonistmusic http://t.co/BNhtxAEZMM

---

Target: 1 (real disaster)
Text:
CHPSRE: RT: Refugees: For our followers in Paris do visit 'A Dream of Humanity' exhibition by rezaphotography ‰Û_ ‰Û_ http://t.co/RPmTROPsVr

---



## Split the data

In [10]:
from sklearn.model_selection import train_test_split

train_sentences, val_sentences, train_labels, val_labels  = train_test_split(train_df_shuffled["text"].to_numpy(),
                                                                        train_df_shuffled["target"].to_numpy(),
                                                                        test_size=0.1, # dedicate 10% of samples to validation set
                                                                        random_state=42)


In [11]:
len(train_sentences), len(train_labels), len(val_sentences), len(val_labels)

(6851, 6851, 762, 762)

In [12]:
train_sentences[:10], train_labels[:10] 

(array(['@mogacola @zamtriossu i screamed after hitting tweet',
        'Imagine getting flattened by Kurt Zouma',
        '@Gurmeetramrahim #MSGDoing111WelfareWorks Green S welfare force ke appx 65000 members har time disaster victim ki help ke liye tyar hai....',
        "@shakjn @C7 @Magnums im shaking in fear he's gonna hack the planet",
        'Somehow find you and I collide http://t.co/Ee8RpOahPk',
        '@EvaHanderek @MarleyKnysh great times until the bus driver held us hostage in the mall parking lot lmfao',
        'destroy the free fandom honestly',
        'Weapons stolen from National Guard Armory in New Albany still missing #Gunsense http://t.co/lKNU8902JE',
        '@wfaaweather Pete when will the heat wave pass? Is it really going to be mid month? Frisco Boy Scouts have a canoe trip in Okla.',
        'Patient-reported outcomes in long-term survivors of metastatic colorectal cancer - British Journal of Surgery http://t.co/5Yl4DC1Tqt'],
       dtype=object), array([0, 

In [13]:
import tensorflow as tf 
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

text_vectorizer = TextVectorization(max_tokens=10000,
                                    output_mode='int',
                                    output_sequence_length=15)
text_vectorizer

In [14]:
text_vectorizer.adapt(train_sentences)

In [15]:
sample_sen = "this is sample sentence"
text_vectorizer([sample_sen])

<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[  19,    9, 8839,    1,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0]])>

## Baseline model

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

model_0 = Pipeline([
    ("tfid", TfidfVectorizer()),
    ("clf", MultinomialNB())
])

model_0.fit(train_sentences, train_labels)

Pipeline(steps=[('tfid', TfidfVectorizer()), ('clf', MultinomialNB())])

In [17]:
baseline_score = model_0.score(val_sentences, val_labels)
baseline_score

0.7926509186351706

## Model With LSTM

In [18]:
import tensorflow.keras.layers as layers
tf.random.set_seed(42)

model_1_embedding = tf.keras.layers.Embedding(input_dim=10000,
                                              output_dim=128,
                                              embeddings_initializer="uniform",
                                              input_length=15)

inputs= tf.keras.layers.Input(shape=(1,), dtype="string")
x = text_vectorizer(inputs)
x = model_1_embedding(x)
print(x.shape)
x = layers.LSTM(64)(x)
output = layers.Dense(1, activation='sigmoid')(x)
model_1 = tf.keras.models.Model(inputs, output)
model_1.summary()

(None, 15, 128)
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization (TextVec  (None, 15)               0         
 torization)                                                     
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 lstm (LSTM)                 (None, 64)                49408     
                                                                 
 dense (Dense)               (None, 1)                 65        
                                                                 
Total params: 1,329,473
Trainable params: 1,329,473
Non-trainable params: 0
___________________________________

In [19]:
model_1.compile(loss = 'binary_crossentropy',
                optimizer = tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [20]:
model_1_hist = model_1.fit(train_sentences, train_labels, epochs=5,
            validation_data= (val_sentences, val_labels))

Epoch 1/5
215/215 [==============================] - 10s 12ms/step - loss: 0.5100 - accuracy: 0.7416 - val_loss: 0.4566 - val_accuracy: 0.7822
Epoch 2/5
215/215 [==============================] - 2s 11ms/step - loss: 0.3176 - accuracy: 0.8717 - val_loss: 0.5138 - val_accuracy: 0.7756
Epoch 3/5
215/215 [==============================] - 2s 11ms/step - loss: 0.2201 - accuracy: 0.9152 - val_loss: 0.5858 - val_accuracy: 0.7677
Epoch 4/5
215/215 [==============================] - 2s 10ms/step - loss: 0.1556 - accuracy: 0.9428 - val_loss: 0.6041 - val_accuracy: 0.7743
Epoch 5/5
215/215 [==============================] - 3s 12ms/step - loss: 0.1076 - accuracy: 0.9594 - val_loss: 0.8746 - val_accuracy: 0.7507


In [21]:
model_1_preds = model_1.predict(val_sentences)
model_1_preds[:10], model_1_preds.shape

(array([[0.00712599],
        [0.78736776],
        [0.9996376 ],
        [0.05679168],
        [0.00258219],
        [0.9996238 ],
        [0.92170197],
        [0.9997993 ],
        [0.9994954 ],
        [0.66457385]], dtype=float32), (762, 1))

In [22]:
model1_preds = tf.squeeze(tf.round(model_1_preds))
model1_preds

<tf.Tensor: shape=(762,), dtype=float32, numpy=
array([0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1.,
       1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0.,
       0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0.,
       1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0.,
       0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0.,
       1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1.,
       0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0

In [23]:
val_sentences[-5:], val_labels[-5:], model1_preds[-5:].numpy()

(array(["That's the ultimate road to destruction",
        '@SetZorah dad why dont you claim me that mean that not right we look the same same eyes same blood same xbox 360 SMH -.-',
        'FedEx will no longer transport bioterror pathogens in wake of anthrax lab mishaps http://t.co/lHpgxc4b8J',
        'Crack in the path where I wiped out this morning during beach run. Surface wounds on left elbow and right knee. http://t.co/yaqRSximph',
        'I liked a @YouTube video from @dannyonpc http://t.co/AAuIzGGc9Q Battlefield Hardline - 11 NEW WEAPONS - New map - Throwingknifes!'],
       dtype=object),
 array([0, 0, 0, 0, 0]),
 array([1., 1., 1., 0., 0.], dtype=float32))

## Model 2 using gru

In [24]:
tf.random.set_seed(42)
from tensorflow.keras import layers
model_2_embedding = layers.Embedding(input_dim = 10000,
                                     output_dim = 128,
                                     name="embedding_2")

inputs = layers.Input(shape=(1,), dtype="string")
x = text_vectorizer(inputs)
x = model_2_embedding(x)
x = layers.GRU(64)(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
model_2 = tf.keras.models.Model(inputs, outputs)
model_2.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization (TextVec  (None, 15)               0         
 torization)                                                     
                                                                 
 embedding_2 (Embedding)     (None, 15, 128)           1280000   
                                                                 
 gru (GRU)                   (None, 64)                37248     
                                                                 
 dense_1 (Dense)             (None, 1)                 65        
                                                                 
Total params: 1,317,313
Trainable params: 1,317,313
Non-trainable params: 0
_________________________________________________

In [25]:
model_2.compile(loss = "binary_crossentropy",
                optimizer = tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [26]:
model_2_hist = model_2.fit(train_sentences, train_labels, epochs=5,
            validation_data=(val_sentences, val_labels))

Epoch 1/5
215/215 [==============================] - 3s 8ms/step - loss: 0.5242 - accuracy: 0.7314 - val_loss: 0.4553 - val_accuracy: 0.7769
Epoch 2/5
215/215 [==============================] - 1s 6ms/step - loss: 0.3195 - accuracy: 0.8694 - val_loss: 0.4937 - val_accuracy: 0.7808
Epoch 3/5
215/215 [==============================] - 1s 6ms/step - loss: 0.2197 - accuracy: 0.9181 - val_loss: 0.5607 - val_accuracy: 0.7743
Epoch 4/5
215/215 [==============================] - 1s 6ms/step - loss: 0.1599 - accuracy: 0.9441 - val_loss: 0.6220 - val_accuracy: 0.7782
Epoch 5/5
215/215 [==============================] - 1s 6ms/step - loss: 0.1221 - accuracy: 0.9584 - val_loss: 0.6205 - val_accuracy: 0.7677


In [27]:
model_preds = model_2.predict(val_sentences)
model_preds[:10],model_preds.shape

(array([[0.33325273],
        [0.87741184],
        [0.9980252 ],
        [0.11561754],
        [0.01235959],
        [0.9925639 ],
        [0.6214264 ],
        [0.99813336],
        [0.9982377 ],
        [0.5018108 ]], dtype=float32), (762, 1))

In [28]:
preds = tf.squeeze(tf.round(model_preds))
preds[:10], preds.shape

(<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 1., 0., 0., 1., 1., 1., 1., 1.], dtype=float32)>,
 TensorShape([762]))

In [29]:
val_sentences[:10], val_labels[:10], preds[:10]

(array(['DFR EP016 Monthly Meltdown - On Dnbheaven 2015.08.06 http://t.co/EjKRf8N8A8 #Drum and Bass #heavy #nasty http://t.co/SPHWE6wFI5',
        'FedEx no longer to transport bioterror germs in wake of anthrax lab mishaps http://t.co/qZQc8WWwcN via @usatoday',
        'Gunmen kill four in El Salvador bus attack: Suspected Salvadoran gang members killed four people and wounded s... http://t.co/CNtwB6ScZj',
        '@camilacabello97 Internally and externally screaming',
        'Radiation emergency #preparedness starts with knowing to: get inside stay inside and stay tuned http://t.co/RFFPqBAz2F via @CDCgov',
        'Investigators rule catastrophic structural failure resulted in 2014 Virg.. Related Articles: http://t.co/Cy1LFeNyV8',
        'How the West was burned: Thousands of wildfires ablaze in #California alone http://t.co/iCSjGZ9tE1 #climate #energy http://t.co/9FxmN0l0Bd',
        "Map: Typhoon Soudelor's predicted path as it approaches Taiwan; expected to make landfall over so

## Model 3 bidirectional lstm

In [30]:
tf.random.set_seed(42)
model_3_embedding = layers.Embedding(input_dim= 10000,
                                     output_dim = 128,
                                     name = "embedding_3")
inputs = layers.Input(shape=(1,),dtype="string")
x = text_vectorizer(inputs)
x = model_3_embedding(x)
x = layers.Bidirectional(layers.LSTM(64))(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
model_3 = tf.keras.models.Model(inputs, outputs)
model_3.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization (TextVec  (None, 15)               0         
 torization)                                                     
                                                                 
 embedding_3 (Embedding)     (None, 15, 128)           1280000   
                                                                 
 bidirectional (Bidirectiona  (None, 128)              98816     
 l)                                                              
                                                                 
 dense_2 (Dense)             (None, 1)                 129       
                                                                 
Total params: 1,378,945
Trainable params: 1,378,945
Non-tra

In [31]:
model_3.compile(loss = "binary_crossentropy",
                optimizer = tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [32]:
model_3.fit(train_sentences, train_labels, epochs=5,
            validation_data=(val_sentences, val_labels))

Epoch 1/5
215/215 [==============================] - 5s 11ms/step - loss: 0.5093 - accuracy: 0.7481 - val_loss: 0.4606 - val_accuracy: 0.7795
Epoch 2/5
215/215 [==============================] - 2s 8ms/step - loss: 0.3135 - accuracy: 0.8708 - val_loss: 0.5144 - val_accuracy: 0.7690
Epoch 3/5
215/215 [==============================] - 2s 8ms/step - loss: 0.2150 - accuracy: 0.9178 - val_loss: 0.5626 - val_accuracy: 0.7677
Epoch 4/5
215/215 [==============================] - 2s 8ms/step - loss: 0.1523 - accuracy: 0.9469 - val_loss: 0.6365 - val_accuracy: 0.7769
Epoch 5/5
215/215 [==============================] - 2s 8ms/step - loss: 0.1083 - accuracy: 0.9639 - val_loss: 0.6509 - val_accuracy: 0.7664


In [33]:
model_3_preds = model_3.predict(val_sentences)
model_3_preds[:10], model_3_preds.shape

(array([[0.04000056],
        [0.8279291 ],
        [0.99842227],
        [0.13531096],
        [0.00311338],
        [0.99220747],
        [0.9552836 ],
        [0.99945647],
        [0.99898285],
        [0.2814168 ]], dtype=float32), (762, 1))

In [34]:
preds = tf.squeeze(tf.round(model_3_preds))
preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 1., 0., 0., 1., 1., 1., 1., 0.], dtype=float32)>

In [35]:
val_sentences[:10],val_labels[:10], preds[:10]

(array(['DFR EP016 Monthly Meltdown - On Dnbheaven 2015.08.06 http://t.co/EjKRf8N8A8 #Drum and Bass #heavy #nasty http://t.co/SPHWE6wFI5',
        'FedEx no longer to transport bioterror germs in wake of anthrax lab mishaps http://t.co/qZQc8WWwcN via @usatoday',
        'Gunmen kill four in El Salvador bus attack: Suspected Salvadoran gang members killed four people and wounded s... http://t.co/CNtwB6ScZj',
        '@camilacabello97 Internally and externally screaming',
        'Radiation emergency #preparedness starts with knowing to: get inside stay inside and stay tuned http://t.co/RFFPqBAz2F via @CDCgov',
        'Investigators rule catastrophic structural failure resulted in 2014 Virg.. Related Articles: http://t.co/Cy1LFeNyV8',
        'How the West was burned: Thousands of wildfires ablaze in #California alone http://t.co/iCSjGZ9tE1 #climate #energy http://t.co/9FxmN0l0Bd',
        "Map: Typhoon Soudelor's predicted path as it approaches Taiwan; expected to make landfall over so

## Model 4 Conv1D

In [36]:
model_4_embedding = layers.Embedding(input_dim=10000,
                                     output_dim = 128,
                                     name = "model_5_embedding")

inputs = layers.Input(shape=(1,), dtype="string")
x = text_vectorizer(inputs)
x = model_4_embedding(x)
x = layers.Conv1D(filters=32, kernel_size=3, activation="relu")(x)
x = layers.GlobalMaxPool1D()(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
model_4 = tf.keras.models.Model(inputs, outputs)
model_4.summary()

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization (TextVec  (None, 15)               0         
 torization)                                                     
                                                                 
 model_5_embedding (Embeddin  (None, 15, 128)          1280000   
 g)                                                              
                                                                 
 conv1d (Conv1D)             (None, 13, 32)            12320     
                                                                 
 global_max_pooling1d (Globa  (None, 32)               0         
 lMaxPooling1D)                                                  
                                                           

In [37]:
model_4.compile(loss = 'binary_crossentropy',
                optimizer = tf.keras.optimizers.Adam(),
                metrics = ["accuracy"])

In [46]:
model_4_hist = model_4.fit(train_sentences, train_labels, epochs=5,
                           validation_data = (val_sentences,val_labels))

Epoch 1/5
215/215 [==============================] - 1s 6ms/step - loss: 0.0857 - accuracy: 0.9714 - val_loss: 0.6824 - val_accuracy: 0.7703
Epoch 2/5
215/215 [==============================] - 1s 5ms/step - loss: 0.0696 - accuracy: 0.9758 - val_loss: 0.7277 - val_accuracy: 0.7638
Epoch 3/5
215/215 [==============================] - 1s 5ms/step - loss: 0.0639 - accuracy: 0.9766 - val_loss: 0.7488 - val_accuracy: 0.7795
Epoch 4/5
215/215 [==============================] - 1s 5ms/step - loss: 0.0569 - accuracy: 0.9796 - val_loss: 0.7791 - val_accuracy: 0.7638
Epoch 5/5
215/215 [==============================] - 2s 9ms/step - loss: 0.0518 - accuracy: 0.9793 - val_loss: 0.7924 - val_accuracy: 0.7848


In [39]:
model_4_preds = model_4.predict(val_sentences)
model_4_preds[:10]

array([[0.3325793 ],
       [0.7092612 ],
       [0.99961483],
       [0.03091617],
       [0.01642669],
       [0.92114055],
       [0.97701573],
       [0.9982546 ],
       [0.99850106],
       [0.04937348]], dtype=float32)

In [40]:
preds = tf.squeeze(tf.round(model_4_preds))
val_sentences[:10],val_labels[:10],preds[:10]

(array(['DFR EP016 Monthly Meltdown - On Dnbheaven 2015.08.06 http://t.co/EjKRf8N8A8 #Drum and Bass #heavy #nasty http://t.co/SPHWE6wFI5',
        'FedEx no longer to transport bioterror germs in wake of anthrax lab mishaps http://t.co/qZQc8WWwcN via @usatoday',
        'Gunmen kill four in El Salvador bus attack: Suspected Salvadoran gang members killed four people and wounded s... http://t.co/CNtwB6ScZj',
        '@camilacabello97 Internally and externally screaming',
        'Radiation emergency #preparedness starts with knowing to: get inside stay inside and stay tuned http://t.co/RFFPqBAz2F via @CDCgov',
        'Investigators rule catastrophic structural failure resulted in 2014 Virg.. Related Articles: http://t.co/Cy1LFeNyV8',
        'How the West was burned: Thousands of wildfires ablaze in #California alone http://t.co/iCSjGZ9tE1 #climate #energy http://t.co/9FxmN0l0Bd',
        "Map: Typhoon Soudelor's predicted path as it approaches Taiwan; expected to make landfall over so

## Lets use Pretrained Embeddings using tensroflow hub

### Lets use tensorflow hub

In [ ]:
import tensorflow_hub as hub
pretrained_embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4") 
embed = pretrained_embed(["hello im Amir"])
print(embed)

In [45]:
embed_layer = hub.KerasLayer("https://tfhub.dev/google/universal-sentence-encoder/4",
                              input_shape=[],
                              dtype=tf.string,
                              trainable=True,
                              name="USE")
embed_layer

In [56]:
## BUILD model 5
model_5 = tf.keras.Sequential([
    embed_layer,
    tf.keras.layers.Dense(64, activation="relu"),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

model_5.compile(loss = "binary_crossentropy",
                optimizer = tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [57]:
model_5_hist = model_5.fit(train_sentences, train_labels, epochs=5,
                           validation_data = (val_sentences,val_labels))

Epoch 1/5
215/215 [==============================] - 41s 165ms/step - loss: 0.0822 - accuracy: 0.9834 - val_loss: 0.6645 - val_accuracy: 0.8018
Epoch 2/5
215/215 [==============================] - 34s 156ms/step - loss: 0.0215 - accuracy: 0.9923 - val_loss: 0.7306 - val_accuracy: 0.7835
Epoch 3/5
215/215 [==============================] - 33s 153ms/step - loss: 0.0167 - accuracy: 0.9937 - val_loss: 0.8232 - val_accuracy: 0.8084
Epoch 4/5
215/215 [==============================] - 33s 153ms/step - loss: 0.0117 - accuracy: 0.9947 - val_loss: 0.8483 - val_accuracy: 0.7992
Epoch 5/5
215/215 [==============================] - 33s 153ms/step - loss: 0.0155 - accuracy: 0.9920 - val_loss: 0.8954 - val_accuracy: 0.8018


In [58]:
model_5_preds = model_5.predict(val_sentences)
model_5_preds[:10]

array([[2.6716918e-02],
       [2.4751800e-01],
       [9.9937588e-01],
       [1.8515748e-03],
       [2.6497567e-01],
       [9.9931574e-01],
       [9.9769872e-01],
       [9.9941361e-01],
       [9.9880028e-01],
       [5.5312703e-04]], dtype=float32)

In [60]:
preds = tf.squeeze(tf.round(model_5_preds))
preds[:10], val_sentences[:10], val_labels[:10]

(<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 0., 1., 0., 0., 1., 1., 1., 1., 0.], dtype=float32)>,
 array(['DFR EP016 Monthly Meltdown - On Dnbheaven 2015.08.06 http://t.co/EjKRf8N8A8 #Drum and Bass #heavy #nasty http://t.co/SPHWE6wFI5',
        'FedEx no longer to transport bioterror germs in wake of anthrax lab mishaps http://t.co/qZQc8WWwcN via @usatoday',
        'Gunmen kill four in El Salvador bus attack: Suspected Salvadoran gang members killed four people and wounded s... http://t.co/CNtwB6ScZj',
        '@camilacabello97 Internally and externally screaming',
        'Radiation emergency #preparedness starts with knowing to: get inside stay inside and stay tuned http://t.co/RFFPqBAz2F via @CDCgov',
        'Investigators rule catastrophic structural failure resulted in 2014 Virg.. Related Articles: http://t.co/Cy1LFeNyV8',
        'How the West was burned: Thousands of wildfires ablaze in #California alone http://t.co/iCSjGZ9tE1 #climate #energy http://t.co/9FxmN0l

## Lets Build bert model

In [61]:
!pip install -q tf-models-official==2.7.0

     |████████████████████████████████| 1.8 MB 5.2 MB/s 
     |████████████████████████████████| 43 kB 2.1 MB/s 
     |████████████████████████████████| 5.9 MB 54.5 MB/s 
     |████████████████████████████████| 116 kB 75.1 MB/s 
     |████████████████████████████████| 1.3 MB 57.7 MB/s 
     |████████████████████████████████| 352 kB 77.1 MB/s 
     |████████████████████████████████| 1.1 MB 60.8 MB/s 
     |████████████████████████████████| 238 kB 76.7 MB/s 
     |████████████████████████████████| 99 kB 11.3 MB/s 
     |████████████████████████████████| 578.0 MB 16 kB/s 
     |████████████████████████████████| 4.6 MB 69.3 MB/s 
     |████████████████████████████████| 511.8 MB 9.5 kB/s 
     |████████████████████████████████| 511.7 MB 6.9 kB/s 
     |████████████████████████████████| 511.7 MB 4.3 kB/s 
     |████████████████████████████████| 4.9 MB 40.3 MB/s 


In [65]:
# Use pretrained BERT
hub_layers = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4",
                            input_shape=[],
                            dtype=tf.string,
                            trainable=False,
                            name="BERT")
hub_layers

In [68]:
model_6 = tf.keras.Sequential([
    embed_layer,
    tf.keras.layers.Dense(64, activation="leaky_relu"),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

model_6.compile(loss = "binary_crossentropy",
                optimizer = tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [69]:
model_6_hist = model_6.fit(train_sentences, train_labels, epochs=5,
                           validation_data = (val_sentences,val_labels))

Epoch 1/5
215/215 [==============================] - 37s 156ms/step - loss: 0.0504 - accuracy: 0.9914 - val_loss: 1.0393 - val_accuracy: 0.7585
Epoch 2/5
215/215 [==============================] - 33s 153ms/step - loss: 0.0074 - accuracy: 0.9961 - val_loss: 1.1410 - val_accuracy: 0.7533
Epoch 3/5
215/215 [==============================] - 33s 154ms/step - loss: 0.0089 - accuracy: 0.9950 - val_loss: 0.8490 - val_accuracy: 0.8018
Epoch 4/5
215/215 [==============================] - 33s 154ms/step - loss: 0.0085 - accuracy: 0.9953 - val_loss: 0.7772 - val_accuracy: 0.7703
Epoch 5/5
215/215 [==============================] - 33s 152ms/step - loss: 0.0089 - accuracy: 0.9961 - val_loss: 1.0035 - val_accuracy: 0.7979
